# Generated by Django 4.2.7 on 2026-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ceo_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ceo_signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_reward_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hearing_status',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('partial', 'Partial Hearing Loss'), ('full', 'Full Hearing Loss'), ('impaired', 'Hearing Impaired')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='housing_situation',
            field=models.CharField(blank=True, choices=[('own', 'Own House'), ('rent', 'Rented'), ('lease', 'Leasing'), ('family', 'Living with Family'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_fee_amount',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participant_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participant_signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'USDT'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
