# Generated by Django 4.2.7 on 2026-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_admin_notes_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='challenge_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('under_review', 'Under Review'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
