# Generated by Django 4.2.7 on 2026-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_usertask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10),
        ),
    ]
