# Generated by Django 6.0.4 on 2026-04-18 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_usertask_unique_together_alter_usertask_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task')},
        ),
        migrations.AlterField(
            model_name='usertask',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='reward_amount',
        ),
    ]
